#resolver: lts-15.6
resolver: lts-19.10

packages:
- '.'

# Override default flag values for local packages and extra-deps
flags:
  proteaaudio-sdl:
    example: true
nix:
  enable: false
  packages: [pulseaudio]
  pure: false
